# Training

In [1]:
### lIBRAIRIES

In [2]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from ucimlrepo) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\thoma\desktop\code\formation\remise-niveau\env\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
import pandas as pd

### Téléchargement du jeu de données (x) et y la target à prédire

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
online_retail = fetch_ucirepo(id=352) 
  
# data (as pandas dataframes) 
x = online_retail.data.features 
y = online_retail.data.targets 
  
# metadata 
print(online_retail.metadata) 
  
# variable information 
print(online_retail.variables)

{'uci_id': 352, 'name': 'Online Retail', 'repository_url': 'https://archive.ics.uci.edu/dataset/352/online+retail', 'data_url': 'https://archive.ics.uci.edu/static/public/352/data.csv', 'abstract': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.', 'area': 'Business', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate', 'Sequential', 'Time-Series'], 'num_instances': 541909, 'num_features': 6, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': None, 'index_col': ['InvoiceNo', 'StockCode'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2015, 'last_updated': 'Mon Oct 21 2024', 'dataset_doi': '10.24432/C5BW33', 'creators': ['Daqing Chen'], 'intro_paper': {'ID': 361, 'type': 'NATIVE', 'title': 'Data mining for the online retail industry: A case study of RFM model-based customer segmentation using data mining', 'authors': 'Daqing Chen, Sai Laing Sain, Kun Guo', 'venue': 'Journal of Database Marketing and Customer Strategy Management, Vol. 19, No. 3', 'year': 2012, 'journal': None, 'DOI': '10.1057/dbm.2012.17', 'URL': 'https://www.semanticscholar.org/paper/e43a5a90fa33d419df42e485099f8f08badf2149', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.The company mainly sells unique all-occasion gifts. Many customers of the company are wholesalers.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation. \nStockCode: Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.\nDescription: Product (item) name. Nominal.\nQuantity: The quantities of each product (item) per transaction. Numeric.\t\nInvoiceDate: Invoice Date and time. Numeric, the day and time when each transaction was generated.\nUnitPrice: Unit price. Numeric, Product price per unit in sterling.\nCustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.\nCountry: Country name. Nominal, the name of the country where each customer resides. ", 'citation': None}}
          name     role         type demographic  \
0    InvoiceNo       ID  Categorical        None
1    StockCode       ID  Categorical        None
2  Description  Feature  Categorical        None
3     Quantity  Feature      Integer        None
4  InvoiceDate  Feature         Date        None
5    UnitPrice  Feature   Continuous        None
6   CustomerID  Feature  Categorical        None
7      Country  Feature  Categorical        None

                                         description     units missing_values
0  a 6-digit integral number uniquely assigned to...      None             no
1  a 5-digit integral number uniquely assigned to...      None             no
2                                       product name      None             no
3  the quantities of each product (item) per tran...      None             no
4  the day and time when each transaction was gen...      None             no
5                             product price per unit  sterling             no
6  a 5-digit integral number uniquely assigned to...      None             no
7  the name of the country where each customer re...      None             no

### Aperçu du dataframe et des colonnes de variables

In [4]:
x.head()

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [5]:
x.dtypes

Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

###### Note : on va garder seulement les premières 1000 lignes pour alléger la mémoire vu que c'est de l'entrainement

In [6]:
# x=x[:1000]
x.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

###### Note : au final, on ne supprimera pas les lignes étant donné le projet de prévision avec les séries temp, on a besoin de davantage de lignes pour coder

### Traitement des données (NA,etc...)

In [11]:
x.isna().sum()
x.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

###### Note : on pourrait vouloir leur ajouter une description de consommation ainsi qu'un ID customer mais cela implique un biais si on utilise l'aléatoire pour l'ID par exemple donc on va simplement supprimer la ligne

###### Note : on va donc supprimer toutes les lignes avec des valeurs manquantes

In [12]:
x.dropna(inplace=True)
x.describe()

C:\Users\thoma\AppData\Local\Temp\ipykernel_18708\1062358878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.dropna(inplace=True)

            Quantity      UnitPrice     CustomerID
count  406829.000000  406829.000000  406829.000000
mean       12.061303       3.460471   15287.690570
std       248.693370      69.315162    1713.600303
min    -80995.000000       0.000000   12346.000000
25%         2.000000       1.250000   13953.000000
50%         5.000000       1.950000   15152.000000
75%        12.000000       3.750000   16791.000000
max     80995.000000   38970.000000   18287.000000

### Vérification de la présence de NA après suppression

In [13]:
x.isna().sum()

Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [15]:
x

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...
541904,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# Mission que l'on s'octroie

### Faire des stats descriptives

###### Note : Dans un premier temps, on va garder ce premier df dans une optique d'utiliser les K-means ou autre modèle de ML non supervisé afin de réaliser une segmentation des clients puis on créera un second df qui reprendra le CA par jour du magasin ainsi que les dépenses par clients journalières pour pouvoir prédire le CA mensuel ou hebdo du magasin et tenter d'utiliser les modèles LOF pour voir si le magasin ne présente pas d'activités suspectes

In [17]:
x.dtypes

Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

### Utiliser les Kmeans pour segmenter les clients

###### Note : on copie le dataframe x dans un dataframe temporaire df pour ne pas interférer avec les données puis on va y implémenter une variable motnant qui reprend les sommes dépensées et on modifie aussi les types de colonnes

In [25]:
df=x.copy()
df['Amount']=x['Quantity']*x['UnitPrice']
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [29]:
df['Date']=df['InvoiceDate'].dt.date 
df.drop('InvoiceDate',axis=1,inplace=True)
df

,Description,Quantity,UnitPrice,CustomerID,Country,Amount,Date
0,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom,15.30,2010-12-01
1,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom,20.34,2010-12-01
2,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom,22.00,2010-12-01
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom,20.34,2010-12-01
4,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom,20.34,2010-12-01
...,...,...,...,...,...,...,...
541904,PACK OF 20 SPACEBOY NAPKINS,12,0.85,12680.0,France,10.20,2011-12-09
541905,CHILDREN'S APRON DOLLY GIRL,6,2.10,12680.0,France,12.60,2011-12-09
541906,CHILDRENS CUTLERY DOLLY GIRL,4,4.15,12680.0,France,16.60,2011-12-09
541907,CHILDRENS CUTLERY CIRCUS PARADE,4,4.15,12680.0,France,16.60,2011-12-09
541908,BAKING SET 9 PIECE RETROSPOT,3,4.95,12680.0,France,14.85,2011-12-09

###### Note : étant donné le peu d'information que l'on possède, on n'utilisera pas les Kmeans mais plutot la RFM qui est plus simple et demande moins de ressources data

### RFM

##### Recency --> temps écoulé depuis le dernier achat

###### Note : on part du postulat que la date de référence est la dernière date globale appliquée

###### Note : on calcule aussi la date du dernier achat de chaque client

In [37]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
date_ref=max(df['Date'])
date_client=df.groupby('CustomerID')['Date'].max()

In [34]:
print(date_client.dtype)  # doit afficher datetime64[ns]

object

##### RFM par client

In [38]:
### recency 
R=(date_ref - date_client).dt.days

def get_nbr_transaction(df):
    freq=df.groupby('CustomerID').size()
    return freq

M = df.groupby('CustomerID')['Amount'].sum()

###### Note : on crée un dataframe par client en fonction des 3 indicateurs

In [45]:
rfm=pd.DataFrame({
    'Recency (days)':R,
    'Frequency (transactions)':get_nbr_transaction(df),
    'M ($)':M
})

In [46]:
rfm.head()

            Recency (days)  Frequency (transactions)    M ($)
CustomerID
12346.0                325                         2     0.00
12347.0                  2                       182  4310.00
12348.0                 75                        31  1797.24
12349.0                 18                        73  1757.55
12350.0                310                        17   334.40

### Scoring

###### Note : on divise la population quantiles, score de 1 à 5,  plus le score est élevé, 
###### plus R petit, plus score élevé
###### plus F grand, plus score élevé
###### plus M grand, plus score élevé

In [48]:
rfm['R_score']=pd.qcut(rfm['Recency (days)'],5,labels=[1,2,3,4,5])
rfm['Freq_score']=pd.qcut(rfm['Frequency (transactions)'].rank(method='first'),5,labels=[1,2,3,4,5])
rfm['M_score']=pd.qcut(rfm['M ($)'],5,labels=[1,2,3,4,5])

### Combinaison des scores pour RFM_score

In [51]:
rfm['RFM_score'] = rfm['R_score'].astype(int)*100 + rfm['Freq_score'].astype(int)*10 + rfm['M_score'].astype(int)

### Création d'une variable catégorielle

In [55]:
def Cat(row):
    R = row['R_score']
    F = row['Freq_score']
    M = row['M_score']
    
    if R >= 4 and F >= 4 and M >= 4:
        return "Très bon acheteur"
    elif R >= 4 and F <= 2:
        return "Nouveau client"
    elif F >= 4 and M <= 2:
        return "Fidèle petit dépensier"
    elif R <= 2:
        return "À relancer"
    elif 3 <= R <= 4 and 3 <= F <= 4:
        return "Acheteur régulier"
    elif M >= 4 and F <= 2:
        return "Gros dépensier irrégulier"
    else:
        return "Acheteur moyen"

rfm['Catégorie'] = rfm.apply(Cat, axis=1)

In [56]:
rfm

,Recency (days),Frequency (transactions),M ($),R_score,Freq_score,M_score,RFM_score,Catégorie
CustomerID,,,,,,,,
12346.0,325,2,0.00,5,1,1,511,Nouveau client
12347.0,2,182,4310.00,1,5,5,155,À relancer
12348.0,75,31,1797.24,4,3,4,434,Acheteur régulier
12349.0,18,73,1757.55,2,4,4,244,À relancer
12350.0,310,17,334.40,5,2,2,522,Nouveau client
...,...,...,...,...,...,...,...,...
18280.0,277,10,180.60,5,1,1,511,Nouveau client
18281.0,180,7,80.82,5,1,1,511,Nouveau client
18282.0,7,13,176.60,1,1,1,111,À relancer
18283.0,3,756,2094.88,1,5,5,155,À relancer
18287.0,42,70,1837.28,3,4,4,344,Acheteur régulier